### ISSUE TITLE
Custom middleware getting called multiple times

### ISSUE THREAD

**Issue by TheDarkStrix** [apollo-server-integrations/apollo-server-integration-next#151]
I have configured a middleware via @as-integratons/next as shown below
 
graphql.js
```
import { ApolloServer } from "@apollo/server";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import typeDefs from "@/app/graphql/schema";
import resolvers from "@/app/graphql/rootResolvers";
import allowCors from "@/utils/cors";
import authenticateMiddleware from "@/app/graphql/middleware/auth-middleware";

const apolloServer = new ApolloServer({
  typeDefs,
  resolvers,
  context: async ({ req, res }) => {
    return { req, res };
  },
});

const handler = startServerAndCreateNextHandler(apolloServer, {
  context: async (req, res) => {
    try {
      await authenticateMiddleware(req, res);
      return { req, res };
    } catch (error) {
      return { req, res };
    }
  },
});

export default allowCors(handler);
```

The middleware : 
```
const authenticateMiddleware = async (req, res, next) => {
 console.count('called');
};

export default authenticateMiddleware;
```

The log : 

![image](https://github.com/apollo-server-integrations/apollo-server-integration-next/assets/18639879/6de08ccd-bc59-414c-94c8-a23a0efd09a9)

This it suppose to called so many times ? If the answer is yes. How can i make sure it is called when required ? If there is any more data required to debug this issue , i am happy to provide them .

The issue if i want to send a res.status(401).json({ message: "Unauthorized" }), i get the following error : 
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at _res.setHeader (/home/manoj/Desktop/project-zeus/node_modules/next/dist/server/base-server.js:326:24)
    at /home/manoj/Desktop/project-zeus/node_modules/@as-integrations/next/dist/startServerAndCreateNextHandler.js:114:37
    at step (/home/manoj/Desktop/project-zeus/node_modules/@as-integrations/next/dist/startServerAndCreateNextHandler.js:33:23)
    at Object.next (/home/manoj/Desktop/project-zeus/node_modules/@as-integrations/next/dist/startServerAndCreateNextHandler.js:14:53)
    at fulfilled (/home/manoj/Desktop/project-zeus/node_modules/@as-integrations/next/dist/startServerAndCreateNextHandler.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT',
  page: '/api/graphql'
}
```

Help regarding this is very much appreciated

**Comment by trevor-scheer** [comment]
The `context` function is called for every request. Do you have explorer/sandbox open and is schema polling enabled? If so it's sending an introspection request every couple seconds. You can disable that.

**Comment by arakelovd** [comment]
When you don't have a favicon, the middleware will also hit for that. I saw this issue until I created one.

**Comment by martinnabhan** [comment]
Closing due to inactivity.
